name: Actualizador Mensual de Datos IDEAM
on:
  schedule:
    - cron: '0 5 2 * *'
  workflow_dispatch: 

# 🛡️ Esto le da al bot los permisos necesarios para guardar archivos sin que GitHub lo bloquee
permissions:
  contents: write

jobs:
  actualizar_sihcli:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar Repositorio
      uses: actions/checkout@v4 # ✅ Actualizado para quitar la advertencia de Node

    - name: Configurar Entorno Python
      uses: actions/setup-python@v5 # ✅ Actualizado para quitar la advertencia de Node
      with:
        python-version: '3.10'

    - name: Instalar Dependencias
      run: |
        pip install pandas requests numpy

    - name: Ejecutar Pipeline de Descarga y Agregación
      run: |
        python actualizar_datos.py

    - name: Confirmar y Guardar Cambios en data/
      run: |
        git config --global user.name 'Chaac Bot Actualizador'
        git config --global user.email 'sihcli-bot@cuencaverde.org'
        # ✅ Ahora le decimos que guarde TODOS los archivos que se generen en la carpeta data
        git add data/
        git commit -m "Automatizado: Actualización mensual de datos de lluvia" || echo "Sin cambios detectados"
        git push
