DATABASE_URL = "postgresql://postgres.ldunpssoxvifemoyeuac:SIHCLI-POTER123*@aws-1-us-east-2.pooler.supabase.com:6543/postgres"
# --------------------------------------------------------
# DEJA AL MENOS 2 LÍNEAS EN BLANCO AQUÍ
# ------------------------------------------------------


# ------------------------------------------------------
[supabase]
SUPABASE_URL = "https://ldunpssoxvifemoyeuac.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkdW5wc3NveHZpZmVtb3lldWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzNDk1NzQsImV4cCI6MjA3ODkyNTU3NH0.UDlf1aFBDCR8WS87ldS_D3cUl3g0HVfIVoekn1ZBAkI"


CLAVE_BETA = "Aleph2026" # Clave para que tus colegas entren a la app
CLAVE_ADMIN = "AdminPoter" # Clave exclusiva para ti en el panel


[gcp_service_account]
type = "service_account"
project_id = "sihclim-gee"  # Este déjalo así, es tu ID de proyecto.
private_key_id = "8c361942a8e2bc2cb49b315d6139067d7dab9dac"
# Ojo: la private_key es larguísima y llena de \n. Pégala tal cual, sin espacios extra.
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDMruUVmwMudw2s\n8c319G5vGcw0wdVqVPmwWW3RSUfa5jWna6Ux1DZXJYcmYp+XJ6pKjAcjCeygDx8+\nX5w2pXYpyWx8XQFebaji1AUbXhYoZ8eSu1LUAiaCpnluElaIDmez1kkaBBOQQEyf\nLs39/6Z2WzVCjjt7HSYsGAWqlGndVIP/l1qFjplYYp0pYOg2p09LEc+5g9XIkMeW\nA2XY4usNnKlmuruboZfR2ob0apdSNlSTZ1Ni0cL2RxvVdDciM8/zLmyNJlGnAHeK\n4LpLbEBXNYUzaXLH9aA2yEOzIWvh3VzgBCqpWAPYeS4gslAiWsUIVYlYYZXPAOeE\nIeqQxFmpAgMBAAECggEAHci7ZBv06A+B6W8cQdSKN1eBLBIinID1/m/c943ay2Mh\nXpXe6XPQXnkDBBZo06V9dbCPn00j5hydNsXR5O/J1IXPZ/9eoh+B6lPg1F0qC0Ii\nu9rPUDNp6CwSUm6PseeqtnQRmhwKvrxkietVJUdMsT9PbjplNGKG+faa6HoFN6QA\nlxJj9ys/UkR0jSsUrNSwyCHweEG356Ad8atCIi9j3Fnh4znM3V7S9lF1J0Ftx2uD\nJwols81Ax0enGbCwu1Tv+ZCR1g9swlmVaUK6jY1yND6Lb5ClETzUlTYsQbKfuH8S\ncLHgpv9tflYLcjKc9cKEBDbyZ5DWAPauxqShT+D3yQKBgQDq1tjG5EBKUEBwq8bB\n4DpHUqD5nJ7290NApmvWuH63p+PTIsJPLAwFunHXp6cGncxFcN01sOF93VRHPAZH\nSTyFI4GoJpV+rfbp/+9PfTXiBK1WRC6hSz9j4Q2Qd+eH69wFNwnEfHE24E5OHShY\nxbrFrTIltSufK+Mv26eULE54fQKBgQDfIGxaD6FFZPCjO5aw6O6QoDKmIxAqcSVu\n8WKZyQNHSE7BbnW0Au1bFXOSJCxZzIao4kQxlogjlOB1dETrx6/rKklP3cmQcgdK\nfXM2zPpB4DWJ3crSFLTl9mKZJGloLdHpDf9zL01OOw/xVdQNVlSm2CqNrN5GXrLU\np5FUrJVZnQKBgQC8x4cto1DXLFoQ+NVnBuRyb0b+QVw8dZp3fxDTZC5hXrIzCQ8g\na+0iMbXQQXJwTCtoawk4Xv91mZVlSihV59ahxGA3FwU394q0osvyn1nQXiglX9wI\nRyAnH0QzLWBPEFgnTQ4qCEtObNQl0SSc8B5rSAY278OoSbRwxWeaIl/WVQKBgAcu\nJu57BEiUZ/4Iw9+rj0nOLfMUu8dx3q+ESxUB1/4qQIaPBHCni3Xb6d0xFtBI+ahj\np6gk3PqwJs0A0dr4kRuzP6q3S24/jSaDhPqlfAQ0r+Rg488A5ZVk6WVeO5ojp1al\noavWQNmcovW0Ol+3gH/iAvSONJT1JTIctluQNjotAoGBAJVz1YzmxrlAx2TVqM64\nzzwwQA4wzSgG8i8a3AHPe6M1bBrBdzFYgrgdyCDa165hGzxRhcGzdoiIUdYDlf8n\n36kn2kgNix5FhrmocHssMenxEKt2HCMy5pmy+qIEKhdcXRjoUJoycYiuffAa18yt\nMbLpk36e2QPSGU0cGDCCo0E7\n-----END PRIVATE KEY-----\n"
client_email = "sihclim-gee-stream-app@sihclim-gee.iam.gserviceaccount.com"
client_id = "104396489462463750453"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sihclim-gee-stream-app%40sihclim-gee.iam.gserviceaccount.com"
universe_domain = "googleapis.com"